title: Anirudh S Gopal
logo: /assets/img/headshot_circle.png
#description: text below image
![alt text](https://github.com/AnirudhSGopal/AnirudhSGopal.github.io/blob/1ed25a8ffd0ee8e81fa52bf6e0efdf71


theme: jekyll-theme-minimal
